package io.github.ololx.leetcode.solutions.easy.task389;

/**
 * 389. Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and
 * then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * Example 1:
 * <p>Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.</p>
 *
 * Example 2:
 * <p>Input: s = "", t = "y"
 * Output: "y"</p>
 *
 * Constraints:
 * <ul>
 *      <li>
 *          0 <= s.length <= 1000
 *      </li>
 *      <li>
 *          t.length == s.length + 1
 *      </li>
 *      <li>
 *          s and t consist of lowercase English letters.
 *      </li>
 * </ul>
 *
 * project leetcode-solutions
 * created 06.05.2022 09:52
 *
 * @author Alexander A. Kropotin
 */
public class Solution {

    public char findTheDifference(String s, String t) {
        if (s == null || s.length() == 0) {
            return t.charAt(0);
        }

        char additionalCharacter = t.charAt(t.length() - 1);

        for (int currentCharIndex = 0; currentCharIndex < s.length(); currentCharIndex++) {
            additionalCharacter ^= s.charAt(currentCharIndex) ^ t.charAt(currentCharIndex);
        }

        return additionalCharacter;
    }
}
